language: generic
services:
  - docker
env:
  - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
before_install: |
  echo "Updating docker-compose to version 1.24.1" \
  && curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /tmp/docker-compose \
  && sudo rm /usr/local/bin/docker-compose \
  && sudo mv /tmp/docker-compose /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose 

jobs:
  include:
    - stage: build
      script: cd $TRAVIS_BUILD_DIR && docker build -t imagemonkey-grabcut -f env/docker/Dockerfile.grabcut .
    - # stage name not required, will continue to use `build`
      script: cd $TRAVIS_BUILD_DIR && docker build -t imagemonkey-predict -f env/docker/Dockerfile.predict .
    - # stage name not required, will continue to use `build`
      script: cd $TRAVIS_BUILD_DIR && docker build -t imagemonkey-playground-api -f env/docker/Dockerfile.playground-api .
