version: "3.2"
services:
  redis:
    ports:
      - 6380:6379
    image: redis
  grabcut:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.grabcut
    env_file:
        - ../docker/env.travis
  playground-api:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.playground-api
    env_file:
        - ../docker/env.travis
