FROM python:2.7-stretch

RUN pip install redis opencv-python sentry-sdk 

RUN apt-get update \
	&& apt-get install -y --no-install-recommends python-opencv \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp/grabcut

COPY src/grabcut.py /tmp/grabcut/grabcut.py

CMD [ "python", "-u", "/tmp/grabcut/grabcut.py" ]
