version: "3.2"
services:
  redis:
    ports:
      - 6380:6379
    image: redis
  grabcut:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.grabcut
    env_file:
        - ../docker/env.travis
    volumes:
      - ../../tests/images:/home/imagemonkey-playground/donations
  predict:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.predict
    env_file:
      - ../docker/env.travis
    volumes:
      - ../../training:/home/playground/training
      - ../../predictions:/tmp/predictions
  playground-api:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.playground-api
    volumes:
      - ../../tests/images:/home/imagemonkey-playground/donations
      - ../../predictions:/tmp/predictions
    env_file:
      - ../docker/env.travis
  testing:
    network_mode: host
    build:
      context: "../../"
      dockerfile: env/docker/Dockerfile.testing
    env_file:
      - ../docker/env.travis
